# Generated by Django 5.1.1 on 2024-11-28 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='building',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Строение'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='flat',
            field=models.IntegerField(blank=True, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
