# Generated by Django 5.1.1 on 2024-11-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0002_rename_available_stock_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='Внешний идентификатор'),
            preserve_default=False,
        ),
    ]
