# Generated by Django 5.1.1 on 2025-01-08 20:32

import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0002_alter_category_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='app/products/', verbose_name='Изображение'),
        ),
    ]
