# Generated by Django 5.1.1 on 2025-01-08 20:40

import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='app/images/users/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='app/images/products/', verbose_name='Изображение'),
        ),
    ]
