# Generated by Django 5.1.1 on 2024-11-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_app', '0003_product_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
